### ISSUE TITLE
not work againt apk protected by jiagu

### ISSUE THREAD

**Issue by udumb4r4** [ksg97031/frida-gadget#16]
![Screenshot_2024-01-30-11-53-47-390_com termux](https://github.com/ksg97031/frida-gadget/assets/91528002/38c537af-7683-40e8-937d-3585c2ea7da2)

+cause no main activity in manifest.xml
+jiagu using fake classes.dex
+need to inject fridaG to libjiagu.so file

**Comment by 0xdiass** [comment]
what was your solution @udumb4r4 ?

**Comment by laladlala** [comment]
same problem for me

**Comment by ksg97031** [comment]
While it might be challenging to bypass general APK protectors, what about loading the Frida gadget from the fake dex for now? If anyone can send the related APK to ksg97031@gmail.com, it could help in checking the issue.

**Comment by ksg97031** [comment]
I believe adding the `--main-activity` option will help resolve this issue. 
This option allows you to specify the main activity manually, which can be useful in cases where the main activity is not automatically detected.

After upgrading to version 1.3.9, you can use the `--main-activity` flag to change the activity.

**Comment by 0xdiass** [comment]
Thx, I will try it, then I update here
