### ISSUE TITLE
Seems not working for Apple Silicon processor

### ISSUE THREAD

**Issue by 1mperatore** [ksg97031/frida-gadget#19]
`WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
rosetta error: Unimplemented syscall number 284
 %`

**Comment by ksg97031** [comment]
@Greyb0w1er, thanks for pointing that out. I have added the missing architecture images to address this issue. If you encounter any further problems, please let me know!

https://hub.docker.com/layers/ksg97031/frida-gadget/latest/images/sha256-6d82c4789c2f05f978ed745d5e07b180425dfd0967b7fdb2a7642ea665f8a405?context=repo
