### ISSUE TITLE
application did not start after injection -  Unity VR project apk on Meta Quest 3

### ISSUE THREAD

**Issue by hitfzyangdianshi** [ksg97031/frida-gadget#20]
I build a VR game apk by Unity, and after injection gadget and install it on Quest 3, the game did not start.

architecture: `--arch arm64`

I also tried `--no-res` and `--use-aapt2` , and also did not work.

**Comment by ksg97031** [comment]
@hitfzyangdianshi 
Hello, I have fixed the suspicious code. 
Please try again by upgrading the frida-gadget version to 1.3.8 (`pip install frida-gadget --upgrade`).

If it still doesn't work, please send me the APK to 'ksg97031@gmail.com' and I'll check it.

**Comment by hitfzyangdianshi** [comment]
Hi. I updated my gadget, and tried again. But,  the game still did not start. 


game: `com.SideQuest.Banter` https://sidequestvr.com/app/10831/banter 
original apk: https://drive.google.com/file/d/1fghjHvYGLF8AC6O7_SpRjLtJtAToa2Xn/view?usp=sharing 
logcat: https://drive.google.com/file/d/1XbRf4QqJ3av7uzCe52IaPl2AihK961pB/view?usp=sharing 


This game is developed by Unity, according to the asset info in apk packet.

**Comment by ksg97031** [comment]
@hitfzyangdianshi 
The injection was successful and i couldn't identify the issue from your logcat.

How about trying to change the main activity to UnityPlayerActivity? 
You can do it like this after upgrading to the latest version:
`frida-gadget /Users/ksg/Downloads/com.SideQuest.Banter.apk --main-activity com.unity3d.player.UnityPlayerActivity`

**Comment by hitfzyangdianshi** [comment]
I have changed the main activity to `com.unity3d.player.UnityPlayerActivity`, and the library should be injected (screenshot below). But the game still did not start. 
The `libfrida-gadget-16.2.1-android-arm64.so` is located in `.apk\lib\arm64-v8a`.

![image](https://github.com/ksg97031/frida-gadget/assets/10493326/343cac1a-27cb-42c9-be17-e1f8049dafca)


![image](https://github.com/ksg97031/frida-gadget/assets/10493326/cc16685f-cf88-400e-b4d7-7cfca7513f19)

It seems that there is another user having met a similar issue before (https://github.com/ksg97031/frida-gadget/issues/17 ), but that user had solved the issue (https://github.com/ksg97031/frida-gadget/issues/17#issuecomment-2203248101 ).  That user mentioned that 

> Yes, I solved it with injecting the gadget library manually. I think issues depends on where you inject the library. When gadget library injection made to wrong location, app crashes, freezes or won't even starts.... (At least this was my case.)

but I do not think in my case the gadget library is injected wrong.

**Comment by mironsaid** [comment]
I am facing the same issue, very similar to @hitfzyangdianshi, the app instantly crashed and according to the logcat:

```
11-06 15:12:51.354 28446 28446 D AndroidRuntime: Shutting down VM
11-06 15:12:51.355 28446 28446 E AndroidRuntime: FATAL EXCEPTION: main
11-06 15:12:51.355 28446 28446 E AndroidRuntime: Process: com.riv_wallet, PID: 28446
11-06 15:12:51.355 28446 28446 E AndroidRuntime: java.lang.VerifyError: Verifier rejected class com.riv_wallet.MainActivity: void com.example.appMainActivity.<init>() failed to verify: void com.exampe.app.MainActivity.<init>(): [0x5] Expected initialization on uninitialized reference Precise Reference: java.lang.String (declaration of 'com.riv_wallet.MainActivity' appears in /data/app/~~bQ1BVcUdhV9hsAIcakW6xQ==/com.example.app-bMdH5WZb5maIC_ucA9mNfQ==/base.apk!classes2.dex)
```
