### ISSUE TITLE
How to set frida-gadget.config.so while injecting frida-gadget.so

### ISSUE THREAD

**Issue by rumengsuixin** [ksg97031/frida-gadget#25]

**Comment by ksg97031** [comment]
@rumengsuixin 
Thank you for raising this issue!

You can inject the `frida-gadget.config.so` file using the latest version.
Please upgrade by either applying the latest commit or running `pip install frida-gadget --upgrade`.
Afterward, you can use the `--config` flag, like this: `frida-gadget test/apks/test.apk --config setup.py --sign`.

**Comment by rumengsuixin** [comment]
> @rumengsuixin Thank you for raising this issue!
> 
> You can inject the file using the latest version. Please upgrade by either applying the latest commit or running . Afterward, you can use the flag, like this: .`frida-gadget.config.so``pip install frida-gadget --upgrade``--config``frida-gadget test/apks/test.apk --config setup.py --sign`



> 感谢您提出此问题！
> 
> 您可以使用最新版本注入文件。请通过应用最新的提交或运行 .之后，您可以使用标志，如下所示：.`frida-gadget.config.so``pip install frida-gadget --upgrade``--config``frida-gadget test/apks/test.apk --config setup.py --sign`

Thank you very much for your answer！！
